In [43]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [44]:
# Drop unnecessary  ID columns.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [59]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE             9
AFFILIATION                  6
CLASSIFICATION               6
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [60]:
# Look at APPLICATION_TYPE value counts for binning
application_types = application_df['APPLICATION_TYPE'].value_counts()
application_types

T3                27037
T4                 1542
T6                 1216
T5                 1173
T19                1065
T8                  737
T7                  725
T10                 528
Other_app_type      276
Name: APPLICATION_TYPE, dtype: int64

In [61]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_types.iloc[8:].index)
cutoff = 528

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other_app_type")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3                27037
T4                 1542
T6                 1216
T5                 1173
T19                1065
T8                  737
T7                  725
T10                 528
Other_app_type      276
Name: APPLICATION_TYPE, dtype: int64

In [62]:
# Look at CLASSIFICATION value counts for binning
classification_types = application_df['CLASSIFICATION'].value_counts()
classification_types

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [63]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_types_filtered = classification_types.loc[classification_types > 1]
classification_types_filtered

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [64]:
# Choose a cutoff value and create a list of classifications to be replaced
classifications_to_replace = list(classification_types.iloc[5:].index)
cutoff = 777

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     4144
C3000     1918
Name: CLASSIFICATION, dtype: int64

In [65]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_df = pd.get_dummies(application_df)
dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other_app_type,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [66]:
# Split our preprocessed data into our features and target arrays
y = dummies_df['IS_SUCCESSFUL'].values
x = dummies_df.drop('IS_SUCCESSFUL', axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(x, y)

In [67]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [68]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features_total = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = input_features_total, activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_15 (Dense)            (None, 8)                 344

 dense_16 (Dense)            (None, 5)                 45

 dense_17 (Dense)            (None, 1)                 6

=================================================================
Total params: 395 (1.54 KB)
Trainable params: 395 (1.54 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [69]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [70]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 3ms/step - loss: 0.6170 - accuracy: 0.6948
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5782 - accuracy: 0.7202
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5702 - accuracy: 0.7217
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5664 - accuracy: 0.7222
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5636 - accuracy: 0.7218
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5616 - accuracy: 0.7234
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5605 - accuracy: 0.7245
Epoch 8/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5596 - accuracy: 0.7226
Epoch 9/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5587 - accuracy: 0.7255
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5587 - accuracy: 0.7245
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5579 - accuracy: 0.7254
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5576 - accuracy: 0.7262
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5575 - accuracy: 0.7255
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5568 - accuracy: 0.7262
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5568 - accuracy: 0.7259
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5566 - accuracy: 0.7270
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5565 - accuracy: 0.7269
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5564 - accuracy: 0.7269
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5565 - accuracy: 0.7262
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5560 - accuracy: 0.7257
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5559 - accuracy: 0.7257
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5560 - accuracy: 0.7256
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5558 - accuracy: 0.7265
Epoch 24/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5560 - accuracy: 0.7261
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5556 - accuracy: 0.7270
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5554 - accuracy: 0.7274
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5556 - accuracy: 0.7257
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5550 - accuracy: 0.7272
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5551 - accuracy: 0.7277
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5550 - accuracy: 0.7269
Epoch 31/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5551 - accuracy: 0.7264
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5551 - accuracy: 0.7273
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5554 - accuracy: 0.7268
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5547 - accuracy: 0.7271
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5550 - accuracy: 0.7274
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5548 - accuracy: 0.7284
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5549 - accuracy: 0.7273
Epoch 38/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5548 - accuracy: 0.7268
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5548 - accuracy: 0.7268
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5548 - accuracy: 0.7273
Epoch 41/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5547 - accuracy: 0.7269
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5546 - accuracy: 0.7272
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5548 - accuracy: 0.7264
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5547 - accuracy: 0.7275
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5543 - accuracy: 0.7277
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5546 - accuracy: 0.7275
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5545 - accuracy: 0.7262
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5546 - accuracy: 0.7275
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5542 - accuracy: 0.7267
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5544 - accuracy: 0.7280
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5541 - accuracy: 0.7279
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5543 - accuracy: 0.7279
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5543 - accuracy: 0.7278
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5541 - accuracy: 0.7277
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5543 - accuracy: 0.7276
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5539 - accuracy: 0.7277
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5539 - accuracy: 0.7278
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5541 - accuracy: 0.7277
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5541 - accuracy: 0.7276
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5538 - accuracy: 0.7278
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5540 - accuracy: 0.7280
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5536 - accuracy: 0.7280
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5538 - accuracy: 0.7269
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5535 - accuracy: 0.7279
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5536 - accuracy: 0.7281
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5538 - accuracy: 0.7275
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5537 - accuracy: 0.7269
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5537 - accuracy: 0.7279
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5534 - accuracy: 0.7280
Epoch 70/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5532 - accuracy: 0.7265
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5535 - accuracy: 0.7279
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5535 - accuracy: 0.7283
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5535 - accuracy: 0.7283
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5535 - accuracy: 0.7284
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5530 - accuracy: 0.7278
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5535 - accuracy: 0.7276
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5534 - accuracy: 0.7282
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5535 - accuracy: 0.7280
Epoch 79/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5533 - accuracy: 0.7275
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5533 - accuracy: 0.7288
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5533 - accuracy: 0.7281
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5530 - accuracy: 0.7280
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5530 - accuracy: 0.7281
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5531 - accuracy: 0.7283
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5530 - accuracy: 0.7275
Epoch 86/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5530 - accuracy: 0.7274
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5530 - accuracy: 0.7285
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5530 - accuracy: 0.7282
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5529 - accuracy: 0.7280
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5530 - accuracy: 0.7281
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5529 - accuracy: 0.7288
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5528 - accuracy: 0.7283
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5526 - accuracy: 0.7285
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5528 - accuracy: 0.7289
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5530 - accuracy: 0.7282
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5525 - accuracy: 0.7281
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5527 - accuracy: 0.7285
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5526 - accuracy: 0.7285
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5528 - accuracy: 0.7289
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5526 - accuracy: 0.7279

In [71]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5463 - accuracy: 0.7397 - 451ms/epoch - 2ms/step
Loss: 0.5463381409645081, Accuracy: 0.7397084832191467

In [ ]:
# Export our model to HDF5 file
filepath = r"/content/drive/MyDrive/AlphabetSoupCharity_Optimized.h5"
nn.save(filepath, save_format='h5')